/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Clients;

/**
 * Classe que define um enumerado constituido por todos os estados possiveis do
 * programa. Estes estados vão funcionar como funções a passar ao servidor
 *
 * @author Miguel Maia
 */
public enum MsgType {

    PLACEABET, GETBETS, HONOURTHEBETS, GOCOLLECTTHEGAINS, CALCULATETOTALBETVALUE, GETTOTALBETVALUE, PROCEEDTOSTARTLINE, HASFINISHLINEBEENCROSSED, STARTRACE,
    MAKEAMOVE, GETHORSEJUMP, SETHORSEJUMP, GETNSPECTATES, SETNSPECTATES, GETNHORSES, SETNHORSES, GETNRACES, SETNRACES, GETDISTANCIA, SETDISTANCIA, GETHORSEWINNERID,
    SETHORSEWINNERID, GETNWINNERS, SETNWINNERS, GETCURRENTRACE, SETCURRENTRACE, GETBETSPERPUNTER, SETBETSPERPUNTER, GETBETBYPUNTERID, RESETBETSPERID, GETHORSESPOSITIONS,
    SETHORSESPOSITIONS, GETRACEFINISHED, SETRACEFINISHED, WAITFORNEXTRACE, CALLPUNTERS, WATCHTHERACE, REPORTRESULTS, HAVEIWON, PROCEEDTOPADDOCK, GOCHECKHORSES,
    PROCEEDTOSTABLE, CALLTOPADDOCK, CLOSE, LOG, SUMMONHORSESTOPADDOCK;
}
